name: Build Documentation

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install doxygen
      run: sudo apt-get install doxygen doxygen-doc doxygen-latex doxygen-gui graphviz cmake
    - name: Install doxygen
      run: |
        cat > CMakeLists.txt <<\EOF
        add_subdirectory(doc)
        EOF
        cmake .
        make doc
